- name: System | Grub | Add custom grub file
  become: true
  ansible.builtin.template:
    src: grub.j2
    dest: /etc/default/grub
    mode: '0644'
  when: ansible_facts['distribution'] == "Debian"

- name: System | Grub | Update grub
  become: true
  ansible.builtin.command:
    cmd: update-grub2
  when: ansible_facts['distribution'] == "Debian"
    