- name: System | Utilities | Install utilities
  become: true
  ansible.builtin.package:
    name:
      - mpv
      - vim
      - fzf
      - dfc
      - zip
      - curl
      - tmux
      - htop
      - kitty
      - rsync
      - meson
      - neovim
      - ripgrep
    state: present

- name: System | Utilities | Install Debian-specific utilities
  become: true
  ansible.builtin.package:
    name: ufw
    state: present
  when: ansible_facts['distribution'] == "Debian"